language: node_js
node:
  - 12
deploy:
  provider: gae
  keyfile: ncd.json
  project: node-ci-cd-poc
  true: master
before_install:
  - openssl aes-256-cbc -K $encrypted_63d8deefa012_key -iv $encrypted_63d8deefa012_iv
    -in ncd.json.enc -out ncd.json -d
